// frontend-react/src/components/friend/UserSearch.jsx
import React, { useState } from 'react';
import { Search, UserPlus, Check, Loader2, User } from 'lucide-react';
import { searchUsers } from '@/feature/user/api';
import { sendFriendRequest } from '@/feature/friend/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export default function UserSearch() {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [sentMap, setSentMap] = useState({}); // { userId: true }

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!query.trim()) return;
    
    setLoading(true);
    try {
      const resp = await searchUsers(query);
      if (resp && resp.items) {
        setResults(resp.items);
      } else {
        setResults([]);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleAdd = async (user) => {
    try {
      await sendFriendRequest(user.id);
      setSentMap(prev => ({ ...prev, [user.id]: true }));
    } catch (err) {
      alert('Failed to send request: ' + err.message);
    }
  };

  return (
    <div className="space-y-4 h-full flex flex-col">
      <form onSubmit={handleSearch} className="flex gap-2">
        <Input 
          value={query} 
          onChange={e => setQuery(e.target.value)}
          placeholder="Search by nickname..."
          className="rounded-xl"
        />
        <Button type="submit" disabled={loading} size="icon" className="rounded-xl shrink-0">
          {loading ? <Loader2 className="animate-spin" size={18} /> : <Search size={18} />}
        </Button>
      </form>

      <div className="flex-1 overflow-y-auto space-y-2 pr-1">
        {results.length === 0 && !loading && query && (
          <div className="text-center text-slate-400 py-8 text-sm">No users found.</div>
        )}
        
        {results.map(user => (
          <div key={user.id} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-100">
             <div className="flex items-center gap-3">
               <div className="h-10 w-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold overflow-hidden">
                 {user.avatarUrl ? <img src={user.avatarUrl} className="w-full h-full object-cover"/> : <User size={20} />}
               </div>
               <div>
                 <div className="font-bold text-slate-800 text-sm">{user.nickname}</div>
                 <div className="text-xs text-slate-400 truncate w-32">{user.email}</div>
               </div>
             </div>
             
             {sentMap[user.id] ? (
               <Button size="sm" variant="ghost" className="text-emerald-600 h-8 w-8 p-0" disabled>
                 <Check size={18} />
               </Button>
             ) : (
               <Button size="sm" variant="ghost" onClick={() => handleAdd(user)} className="text-indigo-600 hover:bg-indigo-50 h-8 w-8 p-0">
                 <UserPlus size={18} />
               </Button>
             )}
          </div>
        ))}
      </div>
    </div>
  );
}

// frontend/src/views/profile/UserSearch.vue
<template>
  <div class="mt-8 card bg-base-100 shadow-xl">
    <div class="card-body">
      <h2 class="text-xl font-bold">探索其他用户</h2>
      <!-- 搜索表单 -->
      <form @submit.prevent="handleSearch" class="form-control flex-row gap-2 mt-4">
        <input 
          type="text" 
          v-model="searchQuery"
          placeholder="按昵称或邮箱搜索..." 
          class="input input-bordered w-full" 
          required
        />
        <button type="submit" class="btn btn-primary" :disabled="isSearching">
          <span v-if="isSearching" class="loading loading-spinner"></span>
          搜索
        </button>
      </form>

      <!-- 搜索结果 -->
      <div class="mt-4">
        <div v-if="isSearching && !searchResults" class="text-center p-4">正在搜索中...</div>
        <div v-else-if="searchResults">
          <p class="text-sm text-base-content/60 mb-2">找到 {{ searchResults.total }} 条结果</p>
          <div v-if="searchResults.items.length > 0" class="space-y-2">
            <!-- 用户列表 -->
            <div 
              v-for="user in searchResults.items" 
              :key="user.id" 
              @click="$emit('viewUser', user.id)"
              class="flex items-center gap-4 p-2 rounded-lg hover:bg-base-200 cursor-pointer transition-colors"
            >
              <div class="avatar">
                <div class="w-12 rounded-full">
                  <img v-if="user.avatarUrl" :src="user.avatarUrl" />
                  <UserCircleIcon v-else class="text-base-content/20" />
                </div>
              </div>
              <div>
                <div class="font-bold">{{ user.nickname }}</div>
                <div class="text-sm text-base-content/60">{{ user.email }}</div>
              </div>
            </div>
          </div>
          <div v-else class="text-center p-4">没有找到匹配的用户。</div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { get } from '../../utils/request';
import { UserCircleIcon } from '@heroicons/vue/24/solid';

const emit = defineEmits(['viewUser']);

const searchQuery = ref('');
const isSearching = ref(false);
const searchResults = ref(null);

const handleSearch = async () => {
  if (!searchQuery.value.trim()) return;
  isSearching.value = true;
  searchResults.value = null;
  try {
    searchResults.value = await get('/users/search/q', {
      params: {
        query: searchQuery.value,
        page: 1,
        pageSize: 20
      }
    });
  } catch (error) {
    console.error("搜索用户失败:", error);
    alert("搜索失败，请稍后重试。");
  } finally {
    isSearching.value = false;
  }
};
</script>
