// frontend-react/src/pages/login/Login.jsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { TomatoCrossSection } from "./components/TomatoCrossSection";
import WelcomeTitle from "./components/WelcomeTitle";
import Testimonial from "./components/Testimonial";

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  return (
    <div className="min-h-screen flex items-center justify-center bg-background relative overflow-hidden">
      {/* 装饰性圆形背景 - 左侧大圆 */}
      <div className="absolute left-[-20vw] top-[10vh] w-[80vw] h-[80vw] max-w-[80vh] max-h-[80vh] opacity-30">
        <TomatoCrossSection />
      </div>
      
      {/* 主容器：上下布局 */}
      <div className="container mx-auto px-4 flex flex-col min-h-screen py-12 z-10 relative">
        {/* 上方：登录表单 */}
        <div className="flex-1 flex items-center justify-center">
          <div className="bg-transparent p-8 rounded-lg w-full max-w-md">
            <WelcomeTitle />
            <form className="space-y-6">
              <div>
                <Input
                  type="email"
                  placeholder="Email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full border-0 border-b border-primary bg-transparent rounded-none px-0 focus-visible:ring-0 focus-visible:ring-offset-0 text-primary placeholder:text-primary/70 focus-visible:border-primary/80"
                />
              </div>
              <div>
                <Input
                  type="password"
                  placeholder="Password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full border-0 border-b border-primary bg-transparent rounded-none px-0 focus-visible:ring-0 focus-visible:ring-offset-0 text-primary placeholder:text-primary/70 focus-visible:border-primary/80"
                />
              </div>
              <Button 
                type="submit" 
                variant="outline"
                className="w-full bg-background text-primary border-primary hover:bg-primary hover:text-white hover:border-primary transition-colors"
              >
                login
              </Button>
              <div className="flex justify-between items-center mt-6 text-sm">
                <Button 
                  asChild
                  variant="ghost"
                  className="text-primary hover:text-primary/80 hover:bg-transparent p-0 h-auto"
                >
                  <Link to="/register">
                    Register
                  </Link>
                </Button>
                <Button 
                  asChild
                  variant="ghost"
                  className="text-primary hover:text-primary/80 hover:bg-transparent p-0 h-auto"
                >
                  <Link to="/forget-password">
                    Forget Password
                  </Link>
                </Button>
              </div>
            </form>
          </div>
        </div>

        {/* 下方：客户评价 - 居右显示 */}
        <div className="flex justify-end pb-12">
          <div className="w-full max-w-md">
            <Testimonial />
          </div>
        </div>
      </div>
    </div>
  );
}

export default Login;

// src/views/login/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-custom-gray dark:bg-custom-gray relative overflow-hidden">
    <!-- 左侧大圆 -->
    <div class="absolute left-[-20vw] top-[10vh] w-[80vw] h-[80vw] max-w-[80vh] max-h-[80vh] bg-yellow-400 rounded-full"></div>
    <!-- 小绿圆 -->
    <div class="absolute left-[5vw] top-[10vh] w-[8vw] h-[8vw] max-w-[8vh] max-h-[8vh] bg-lime-600 rounded-full"></div>
    <!-- 登录卡片 -->
    <div class="bg-transparent p-[2vw] rounded-lg z-10 w-[28vw] min-w-[250px]">
      <h1 class="text-green-700 text-[5vw] min-text-[24px] font-bold-600  mb-[2vw] left-[-25vw] -translate-y-[4vw]">login</h1>
      <form @submit.prevent="handleLogin" class="space-y-[2vw]">
        <div>
          <input
            v-model="email"
            type="text"
            placeholder="Email"
            class="w-full 
            border-b 
            border-green-700 
            bg-transparent 
            outline-none 
            text-green-500 
            dark:text-green-400 
            placeholder-green-700 
            dark:placeholder-green-400 
            focus:border-green-500 
            focus:placeholder-green-500"
          />
        </div>
        <div>
          <input
            v-model="password"
            type="password"
            placeholder="Password"
            class="w-full border-b 
            border-green-700 
            bg-transparent 
            outline-none 
            text-green-500 
            dark:text-green-400 
            placeholder-green-700 
            dark:placeholder-green-400 
            focus:border-green-500 
            focus:placeholder-green-500"
          />
        </div>
        <button
          type="submit"
          class=" btn btn-outline w-full bg-custom-white dark:bg-green-700 text-green-700 dark:text-green-100 py-[0.8vw] rounded hover:bg-yellow-400 transition"
        >
          login
        </button>
        <div class="flex justify-between mt-4">
          <button
            type="button"
            @click="goRegister"
            class="text-green-700 dark:text-green-400 hover:text-yellow-400"
          >
            Register
          </button>
          <button
            type="button"
            @click="goForgetPassword"
            class="text-green-700 dark:text-green-400 hover:text-yellow-400"
          >
            Forget Password
          </button>
        </div>
      </form>
    </div>
  </div>
</template>



<script setup>
import { ref } from 'vue';
import { post } from '../../utils/request'
import { useUserStore } from '../../store/user';
import { useRouter,useRoute } from 'vue-router';

const email = ref('');
const password = ref('');
const router = useRouter();
const route = useRoute();
const userStore = useUserStore();

const handleLogin = async () => {
  try {
    const res = await post('/auth/login', {
      email:email.value,
      password:password.value,
    });
    if (res.token) {
      userStore.setUser(res.token, res.user)
      localStorage.setItem('token',res.token);
      localStorage.setItem('user', JSON.stringify(res.user))
      const redirect = route.query.redirect || '/home';
      router.push(redirect);
    }
  } catch (err) {
    console.error('登录失败:', err);
  }
};

const goRegister = () => {
  router.push('/register');
};

const goForgetPassword = () => {
  router.push('/forget-password');
};

</script>

<style lang="scss" scoped>

</style>
